---
- hosts: docker
  tasks:
    - name: Stop Container if any
      docker_container:
        name: insuranceapp
        state: stopped
      ignore_errors: true
    - name: deploy insuranceapp docker container
      docker_container:
        image: docker.io/kotianrakshith/insuranceapp
        name: insuranceapp
        state: started
        auto_remove: true
        ports:
          - "8081:8081"
