# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool:
  name: Default

steps:
- task: Maven@4
  inputs:
    mavenPomFile: 'pom.xml'
    publishJUnitResults: false
    javaHomeOption: 'JDKVersion'
    mavenVersionOption: 'Default'
    mavenAuthenticateFeed: false
    effectivePomSkip: false
    sonarQubeRunAnalysis: false
- task: Docker@2
  inputs:
    containerRegistry: 'kotianrakshith'
    repository: 'insuranceapp'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: 
- task: SSH@0
  inputs:
    sshEndpoint: 'capstonevm'
    runOptions: 'inline'
    inline: |
      docker stop insuranceapp 2>/dev/null
      docker rm insuranceapp 2>/dev/null
      docker run -itd -p 8081:8081 --name insuranceapp kotianrakshith.azurecr.io/insuranceapp
    readyTimeout: '20000'

